### ISSUE TITLE
Why does this plugin suck now?

### ISSUE THREAD

**Issue by Waffles2112** [OnlyNoobDied/GadgetsMenu#289]
im serious
theres so many problems
it used to be one of the best and now its just crap and lags even worse

for example
it reset all of my configured messages because of the previously reported auto download bug
and the english its transated in isn't even great/doesnt even make any sense
not to mention all the new permissions that i didnt want to change but i guess i have to now that it keeps auto updating and reseting my configs and force stopping my server

it just sucks

**Comment by OnlyNoobDied** [comment]
I'm so sorry for my previous update that i didn't mention to you all about auto update.

If you're using 3.7, please make sure you have set "auto update" to false instead of "auto-update".

**Comment by Waffles2112** [comment]
im not going to bother with the plugin anymore since i lack the patience to redo all my configurations

**Comment by OnlyNoobDied** [comment]
Can you help me to translate the messages.

**Comment by HellaMixel** [comment]
It's just an update man, it honestly is not that hard to redo the config, in other words he actually made it a lot more convenient and easier to edit than the old plugin. Plugin configurations takes time, and if you " lack the patience to redo all my configurations", then you shouldn't be configuring any plugins. I was extremely pissed off at this new update because all the problems, but he is working on fixing them and he has fixed a major amount of big bugs that I was stressing over. If your server keeps crashing it's because you have an outdated version of WorldGuard. Go download WorldGuard 6.2.1 and get the latest version of GadgetsMenu. After you download the latest version of GadgetsMenu you HAVE to remove the old Folder and Jar File. You can download the old Folder and use it as a rephrase to edit your new config. I had the same problem and I understand exactly where you are coming from, but give the developer some slack. He coded am amazing plugin that I am proud to have on my server and proud to give it to my players. Hopefully this helped you.

**Comment by Waffles2112** [comment]
when i said i lacked the pacience to reconfigure everything
i ment that im very busy with other things
like my engineering, web design, and welding classes im taking
and im just a little upset because my server keeps restarting whenever i start it
so i just removed the plugin all together because im just to busy to deal with anything

**Comment by HellaMixel** [comment]
Well read what I said above, it'll help you out. Take care :) Good luck.

**Comment by OnlyNoobDied** [comment]
@Waffles2112 , @HellaMixel
What do you think of GadgetsMenu now? Is there any improvement, and what do i need to improve?

**Comment by Waffles2112** [comment]
my response would probably be yes but i closed my server since then
and im busy with other things to try it out

**Comment by OnlyNoobDied** [comment]
Okay, thanks a lot. :)
