### ISSUE TITLE
mysters boxs with expire date are infinite

### ISSUE THREAD

**Issue by xion87** [OnlyNoobDied/GadgetsMenu#389]
i just noticed the player that have permission
gadgetsmenu.mysteryboxes.open.5
and i add to him a mysteryboxes 5 with **/gmysteryboxes give %player% 5 5 ex=7d**, it open it, and relog, and voila, box still appaer again and can open it infinite times.

**Comment by maxlehot1234** [comment]
@xion87 I try and have no issue.

The box will still reappear but I get no rewards because the box give no reward.
Box take few seconds to give a reward and display a small animation before.

So if the player relog or the server restart during this, box will return in the player "inventory" and he receive nothing.


Maybe @OnlyNoobDied  can confirm

**Comment by xion87** [comment]
I just noticed this is a issue that happen also with normal crafted, plus i see this error maybe is related?
https://hastebin.com/ocojorolin.sql

**Comment by xion87** [comment]
@OnlyNoobDied

**Comment by OnlyNoobDied** [comment]
Alright, please give me some time to check the problem.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed in version 4.0.16. Please update the plugin.
@xion87
