### ISSUE TITLE
Pet Riding and Praticle Problem

### ISSUE THREAD

**Issue by mckite** [OnlyNoobDied/GadgetsMenu#716]
**Describe the bug**
Particle is not showing correctly for pet rider and, riding pet can ignore obstacles.
Pet isn't following player if the pet is far from player (such as more than 24 blocks)

(See in Video for more specific info)
**To Reproduce**

1. Summon pet and Particles
2. Ride a pet and moving
3. press F5 key

1. Summon pet
2. Ride a pet and moving for obstacles (see in video)

1. Summon pet.
2. Moving quick or warping
3. there are no pet around the player.

I send email (yapz******@gmail.com ) more info 

**Expected behavior**
Particle should show for riders correctly instead of fixing/
Pet cannot ignore obstacles
Pet should follow the player.

**Further Information (please complete the following information):**
 - Server Version:  1.12.2
 - GadgetsMenu Version: 4.5.3
 - Console stack trace if have.0

**Screenshots**

I send email (yapz******@gmail.com ) more info 

**Additional Information**
After updating for pet riding feature.

**Comment by OnlyNoobDied** [comment]
`Particle should show for riders correctly instead of fixing`
This issue can't be fixed in 1.12 server. The only way is update your server to 1.14.4

`Pet cannot ignore obstacles`
Baby pet can pass thru one block, it's normal.

`Pet should follow the player`
This issue will be fixed in the next update.
